# I created a dictionary here to define all the xpaths of the filters,
# The website wasn't showing information for more than 1000 products

paths = {
    "W23": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[2]/label/span[1]",
    "S22": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[3]/label/span[1]",
    "W22": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[4]/label/span[1]",
    "S21": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[5]/label/span[1]",
    "W21": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[6]/label/span[1]",
    "S20": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[7]/label/span[1]",
    "W20": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[8]/label/span[1]",
    "S19": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[9]/label/span[1]",
    "W19": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[10]/label/span[1]",
    "S18": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[11]/label/span[1]",
    "W18": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[12]/label/span[1]",
    "S17": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[13]/label/span[1]",
    "W17": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[14]/label/span[1]",
    "IK12": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[15]/label/span[1]",
    "S16": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[16]/label/span[1]",
    "W16": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[17]/label/span[1]",
    "S15": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[18]/label/span[1]",
    "W15": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[19]/label/span[1]",
    "S14": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[20]/label/span[1]",
    "W14": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[21]/label/span[1]",
    "S13": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[22]/label/span[1]",
    "W13": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[23]/label/span[1]",
    "S12": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[24]/label/span[1]",
    "W12": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[25]/label/span[1]",
    "S11": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[26]/label/span[1]",
    "W11": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[27]/label/span[1]",
    "S10": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[28]/label/span[1]",
    "W10": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[29]/label/span[1]",
    "S09": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[30]/label/span[1]",
    "W09": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[31]/label/span[1]",
    "S08": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[32]/label/span[1]",
    "W08": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[33]/label/span[1]",
    "S07": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[34]/label/span[1]",
    "W07": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[35]/label/span[1]",
    "S06": "/html/body/div[1]/div[2]/section[2]/div/div[1]/div/div[9]/div[36]/label/span[1]"
}
